# Note: Commented out things were to support the `graph auth` test, which
# stopped working after upgrading the dist to Xenial (or Bionic).

dist: bionic
language: node_js
node_js:
  - '10'
  - '11'
cache:
  yarn: false
services:
  - docker
# before_install:
#  - sudo apt-get install libsecret-1-dev dbus gnome-keyring python-keyring python-gnomekeyring
# before_script:
# Create a new 'login' keyring; this appearas to be necessary for gnome-keyring to auto-launch
# properly when needed
# - dbus-launch /usr/bin/python -c "import gnomekeyring;gnomekeyring.create_sync('login', '');"
script:
  - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
  # Run the test suite
  - yarn test
  # Test codegen and build in the example subgraph
  - cd examples/example-subgraph
  - yarn
  - ../../bin/graph codegen --debug
  - ../../bin/graph build --debug
  # Exercise `graph test` with another example subgraph
  - cd ../../examples/basic-event-handlers
  - yarn
  - ../../bin/graph test "yarn test"
  # Run `graph auth` inside `dbus-launch` to be able to access gnome-keyring
  # secrets via keytar
  # - dbus-launch bash -c '../../bin/graph auth http://some-node-ip.org test-access-token'
env:
  global:
    - secure: eFOq9UQXTWRvqkIzu1VwUiG3sRb6v4XA8CDayRmGhx58WWJDw1EoX8tXJ5r8K3aj4sh66LKYD5ONIBFP/DjiH28xnC9EkIGlPfKzwUPxDl+seswgqO2VIiVLRdPpmXS0j1FWfDpqpyBB6q9uUA9nToU/aK6lUKHS+tN0iEdOWn6bw4Q3ruaIygm4oijuXOlPfgCnfQLX4iDtGOq0mpRrcAGI71yVHq8MtV0ou1a63bWo9tCrrDDp2xfPGrwf5gnD0hC3hLyrHQHI0B1Ob8gWlU031/VXiQuDn8/FQGKI3dqCLyuQLM75PhQHK7aAbxXMrC4vAQZ9nECN0ZwJEbfrd4HO7gG22NDMRzixOVVDwkg14HgYGBdrBJKjcp1NTCLZJc/feqmbsNvdoUPJ3NXZoD5UM216V8jboOLX7cH1B3e20xFHCv2sOYYx2PfdczbWHnX1/+vXWyKL0srl4n2GHilDpk9cXuPgNlE5Z184bI0lm+VxEePDKJi+YGXQSHQvj1vH1K3/TAPq2RMoA3ucbuLhgj1K7K7zK1of3usmaB6bGF5vHiE6BJ/0ZdBYTNL1IEtURykqRRDKAu5CDXek3UySTTUmMiU9Qp5iUXfsA9Y3A0qeXbglAfFvfIAOd4wYw53JhhgWiA8uPaI4Oo7k6+ooAUvBGwfzAZ+0Qz7h1Is=
    - secure: IFftP3uYFPjfnUZdTbyaX7dV4e+yKvoh0YLjOd5MpI7+E7bYnjint1xMWGgF06r9Lgqioq1COarTHeerVffj6nygkM7w5CKvFG2bd7Eu3x6YSQDsGkPIiCriureIZzLNemugOTfzWFPm+9jBtNeG+cg8XkgfT/qhqxK6fH4t1xNTNBMu6PXCv+gq/EA/KfTPtwcJxi+upO60i0pWP5YbBUfHJh+Ixigk2blFLBHscFb+kohpCy42IdLME+V8f1XF2xGGQihUqN1/NvnGjyz5zzKDpZT6N0HazJU8JBHUuyDLoTHyFSTHv6EHVTzx3nR2XSToyhpwuW89Zaer5x7/B9zY+EozBKyfcio1ysliJruBFBplXXArpRH9L39wdqX7D+2JhahbkVlcraxENYO5pKKW2Wy6efQk1BC+dDjLCXMDd45BEOQxZGfz47fu6HH17CQmPhqYR13DcDexcyqoypBFEvo2wgzRndWapcivanahjeLy+SOIKbux4ULCyDQsu4t+wd0bwoWKc8ixQZ6xr7f0qR391HDXXwgi8sX40DTT5pQOmn/w2dg+CR14x20MDExL8hhWHQ4RJ2cN7ea8E0IBI96vlM4tshnSBVqSoikig4PKIDde8cnuJ56zMSpZ12CimPjvHmrjfbiF6VKsZYiCTeI912GpyV/8akpuCdY=
