name: Rust CI

on:
  push:
    branches: [main]
    paths:
      - 'packages/napi-utils/**'
  pull_request:
    branches: [main]
    paths:
      - 'packages/napi-utils/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.77.0

      - name: Install Protobuf on macOS
        run: brew install protobuf

      - name: cargo check
        working-directory: packages/napi-utils
        run: |
          cargo check

  test:
    name: Test Suite
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.77.0

      - name: Install Protobuf on macOS
        run: brew install protobuf

      - name: Run tests
        working-directory: packages/napi-utils
        run: cargo test

  fmt:
    name: Rustfmt
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.77.0
      - name: install rustfmt
        working-directory: packages/napi-utils
        run: rustup component add rustfmt
      - name: format
        working-directory: packages/napi-utils
        run: cargo fmt --all -- --check

  clippy:
    name: Clippy
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.77.0
      - name: Install Protobuf on macOS
        run: brew install protobuf
      - name: install clippy
        working-directory: packages/napi-utils
        run: rustup component add clippy
      - name: clippy
        working-directory: packages/napi-utils
        run: cargo clippy -- -D warnings
